# Generated by Django 6.1.1 on 2026-09-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "permissions": (
                    ("can_read", "Can read vehicle information"),
                    ("can_write", "Can create, update or delete vehicle."),
                )
            },
        ),
    ]
