# Generated by Django 6.1.1 on 2026-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_alter_vehicle_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="short_name",
            new_name="country",
        ),
        migrations.AddField(
            model_name="currency",
            name="country_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="currency_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
