# Generated by Django 6.1.1 on 2026-09-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_rename_short_name_currency_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="brand",
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_brand",
                to="vehicle.vehiclebrand",
            ),
        ),
    ]
