# Generated by Django 6.1.1 on 2026-09-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
        ("vehicle", "0004_remove_vehicle_brand_vehiclemodel_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchitem",
            name="unit_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_item_cost_price",
                to="vehicle.vehicleprice",
            ),
        ),
    ]
